# TCL File Generated by Component Editor 11.1sp1
# Sat Jun 09 23:49:10 JST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | avalonif_mmc "mmc" v1.0
# | null 2012.06.09.23:49:10
# | 
# | 
# | D:/home/inouema/work/git/pc-8001onDE0/project/rtl/sub_system/avalonif_mmc.v
# | 
# |    ./avalonif_mmc.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module avalonif_mmc
# | 
set_module_property NAME avalonif_mmc
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME mmc
set_module_property TOP_LEVEL_HDL_FILE avalonif_mmc.v
set_module_property TOP_LEVEL_HDL_MODULE avalonif_mmc
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME avalonif_mmc
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file avalonif_mmc.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter IDLE STD_LOGIC_VECTOR 8
set_parameter_property IDLE DEFAULT_VALUE 8
set_parameter_property IDLE DISPLAY_NAME IDLE
set_parameter_property IDLE TYPE STD_LOGIC_VECTOR
set_parameter_property IDLE UNITS None
set_parameter_property IDLE ALLOWED_RANGES 0:31
set_parameter_property IDLE AFFECTS_GENERATION false
set_parameter_property IDLE HDL_PARAMETER true
add_parameter SDO STD_LOGIC_VECTOR 4
set_parameter_property SDO DEFAULT_VALUE 4
set_parameter_property SDO DISPLAY_NAME SDO
set_parameter_property SDO TYPE STD_LOGIC_VECTOR
set_parameter_property SDO UNITS None
set_parameter_property SDO ALLOWED_RANGES 0:31
set_parameter_property SDO AFFECTS_GENERATION false
set_parameter_property SDO HDL_PARAMETER true
add_parameter SDI STD_LOGIC_VECTOR 2
set_parameter_property SDI DEFAULT_VALUE 2
set_parameter_property SDI DISPLAY_NAME SDI
set_parameter_property SDI TYPE STD_LOGIC_VECTOR
set_parameter_property SDI UNITS None
set_parameter_property SDI ALLOWED_RANGES 0:31
set_parameter_property SDI AFFECTS_GENERATION false
set_parameter_property SDI HDL_PARAMETER true
add_parameter DONE STD_LOGIC_VECTOR 1
set_parameter_property DONE DEFAULT_VALUE 1
set_parameter_property DONE DISPLAY_NAME DONE
set_parameter_property DONE TYPE STD_LOGIC_VECTOR
set_parameter_property DONE UNITS None
set_parameter_property DONE ALLOWED_RANGES 0:31
set_parameter_property DONE AFFECTS_GENERATION false
set_parameter_property DONE HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 address address Input 2
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end MMC_SCK export Output 1
add_interface_port conduit_end MMC_SDO export Output 1
add_interface_port conduit_end MMC_SDI export Input 1
add_interface_port conduit_end MMC_CD export Input 1
add_interface_port conduit_end MMC_WP export Input 1
add_interface_port conduit_end MMC_nCS export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_sender
# | 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave_0
set_interface_property interrupt_sender associatedClock clock

set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender irq irq Output 1
# | 
# +-----------------------------------
