  //Example instantiation for system 'pc8001_sub_system'
  pc8001_sub_system pc8001_sub_system_inst
    (
      .MMC_CD_to_the_mmc_spi               (MMC_CD_to_the_mmc_spi),
      .MMC_SCK_from_the_mmc_spi            (MMC_SCK_from_the_mmc_spi),
      .MMC_SDI_to_the_mmc_spi              (MMC_SDI_to_the_mmc_spi),
      .MMC_SDO_from_the_mmc_spi            (MMC_SDO_from_the_mmc_spi),
      .MMC_WP_to_the_mmc_spi               (MMC_WP_to_the_mmc_spi),
      .MMC_nCS_from_the_mmc_spi            (MMC_nCS_from_the_mmc_spi),
      .areset_to_the_sub_system_pll        (areset_to_the_sub_system_pll),
      .clk_0                               (clk_0),
      .data0_to_the_epcs_flash_controller  (data0_to_the_epcs_flash_controller),
      .dclk_from_the_epcs_flash_controller (dclk_from_the_epcs_flash_controller),
      .in_port_to_the_cmt_din              (in_port_to_the_cmt_din),
      .in_port_to_the_cmt_gpio_in          (in_port_to_the_cmt_gpio_in),
      .in_port_to_the_gpio1                (in_port_to_the_gpio1),
      .locked_from_the_sub_system_pll      (locked_from_the_sub_system_pll),
      .out_port_from_the_cmt_dout          (out_port_from_the_cmt_dout),
      .out_port_from_the_cmt_gpio_out      (out_port_from_the_cmt_gpio_out),
      .out_port_from_the_gpio0             (out_port_from_the_gpio0),
      .phasedone_from_the_sub_system_pll   (phasedone_from_the_sub_system_pll),
      .pll_cpu                             (pll_cpu),
      .pll_io                              (pll_io),
      .pll_peripheral                      (pll_peripheral),
      .pll_sdram                           (pll_sdram),
      .reset_n                             (reset_n),
      .sce_from_the_epcs_flash_controller  (sce_from_the_epcs_flash_controller),
      .sdo_from_the_epcs_flash_controller  (sdo_from_the_epcs_flash_controller),
      .zs_addr_from_the_sdram              (zs_addr_from_the_sdram),
      .zs_ba_from_the_sdram                (zs_ba_from_the_sdram),
      .zs_cas_n_from_the_sdram             (zs_cas_n_from_the_sdram),
      .zs_cke_from_the_sdram               (zs_cke_from_the_sdram),
      .zs_cs_n_from_the_sdram              (zs_cs_n_from_the_sdram),
      .zs_dq_to_and_from_the_sdram         (zs_dq_to_and_from_the_sdram),
      .zs_dqm_from_the_sdram               (zs_dqm_from_the_sdram),
      .zs_ras_n_from_the_sdram             (zs_ras_n_from_the_sdram),
      .zs_we_n_from_the_sdram              (zs_we_n_from_the_sdram)
    );

